name: ci

on: [push]
jobs: 
    build-test:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout 
              uses: actions/checkout@v6
            - name: Cypress Test   
              uses: cypress-io/github-action@v6
              with:
                start: 'npm run dev'
                build: 'npm run build'
            - uses: actions/upload-artifact@v6
              if: always() 
              with:
                name: Cypress Results
                path: |
                    cypress/videos
                    cypress/screenshots
                    cypress/results
                if-no-files-found: ignore      